included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Package.swift

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

analyzer_rules:
  - unused_import

disabled_rules:
  - todo
  - force_cast
  - force_try
  - force_unwrapping

line_length:
  warning: 150
  error: 200

function_body_length:
  warning: 150
  error: 200

type_body_length:
  warning: 500
  error: 600

file_length:
  warning: 800
  error: 1000

cyclomatic_complexity:
  warning: 50
  error: 100

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - im

large_tuple:
  warning: 3
  error: 4

# custom_rules: