name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.8'
        
    - name: Cache Swift packages
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
          
    - name: Run tests
      run: swift test --enable-code-coverage
      
    - name: Generate code coverage report
      run: |
        xcrun llvm-cov export -format="lcov" \
          .build/debug/ContactScrubbyPackageTests.xctest/Contents/MacOS/ContactScrubbyPackageTests \
          -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.lcov
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    name: Build
    runs-on: macos-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.8'
        
    - name: Cache Swift packages
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
          
    - name: Build debug
      run: swift build
      
    - name: Build release
      run: swift build -c release
      
    - name: Test executable
      run: |
        .build/release/contactscrub --help
        .build/release/contactscrub --version
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: contactscrub-${{ github.sha }}
        path: .build/release/contactscrub
        retention-days: 7

  lint:
    name: Lint
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.8'
        
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: Run SwiftLint
      run: swiftlint --strict
      continue-on-error: true

  security:
    name: Security Scan
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run security scan
      run: |
        # Check for common security issues
        echo "Checking for potential security issues..."
        
        # Check for hardcoded secrets (basic scan)
        if grep -r -i "password\|secret\|key\|token" --include="*.swift" Sources/ Tests/ || true; then
          echo "⚠️  Found potential secrets in code - please review"
        fi
        
        # Check for TODO/FIXME security items
        if grep -r -i "todo.*security\|fixme.*security" --include="*.swift" Sources/ Tests/ || true; then
          echo "⚠️  Found security-related TODO/FIXME items"
        fi
        
        echo "✅ Basic security scan completed"

  release:
    name: Release
    runs-on: macos-latest
    needs: [test, build, lint]
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.8'
        
    - name: Build release binary
      run: swift build -c release
      
    - name: Create release archive
      run: |
        mkdir -p release
        cp .build/release/contactscrub release/
        cp README.md release/
        cp LICENSE release/
        tar -czf contactscrub-${{ github.event.release.tag_name }}-macos.tar.gz -C release .
        
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./contactscrub-${{ github.event.release.tag_name }}-macos.tar.gz
        asset_name: contactscrub-${{ github.event.release.tag_name }}-macos.tar.gz
        asset_content_type: application/gzip
        
    - name: Create Homebrew formula
      run: |
        echo "Creating Homebrew formula..."
        ARCHIVE_URL="https://github.com/thieso2/ContactScrubby/releases/download/${{ github.event.release.tag_name }}/contactscrub-${{ github.event.release.tag_name }}-macos.tar.gz"
        ARCHIVE_SHA256=$(shasum -a 256 contactscrub-${{ github.event.release.tag_name }}-macos.tar.gz | cut -d' ' -f1)
        
        cat > contactscrub.rb << EOF
        class Contactscrub < Formula
          desc "A powerful contact scrubbing and management tool for macOS"
          homepage "https://github.com/thieso2/ContactScrubby"
          url "$ARCHIVE_URL"
          sha256 "$ARCHIVE_SHA256"
          version "${{ github.event.release.tag_name }}"
          
          depends_on :macos
          
          def install
            bin.install "contactscrub"
            doc.install "README.md"
          end
          
          test do
            assert_match version.to_s, shell_output("#{bin}/contactscrub --version")
          end
        end
        EOF
        
    - name: Upload Homebrew formula
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./contactscrub.rb
        asset_name: contactscrub.rb
        asset_content_type: text/plain